apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: waha-media
  namespace: apps
spec:
  accessModes: ["ReadWriteOnce"]
  storageClassName: local-path
  resources:
    requests:
      storage: 10Gi
